### ISSUE TITLE
Top Games doesn't show any results

### ISSUE THREAD

**Issue by cprn** [streamlink/streamlink-twitch-gui#411]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Expected / Actual behavior

I expect to see list of games but there's only a count "Top Games (1594)" and "Fetch more" button. Featured and Top Channels show correctly. I currently have no other machine to check but it's fresh install with no proxy, etc., default settings.

### Reproduction steps

1. install Manjaro.i3
2. install from `yaourt -S streamlink-twitch-gui` (or `streamlink-twitch-gui-git`, neither works)
3. run `streamlink-twitch-gui`
4. go to Top Games

### Environment details (operating system, etc.)

Up-to-date Manjaro.i3 16.10 (windows manager only)

### Comments, logs, screenshots, etc.

![image](https://cloud.githubusercontent.com/assets/6132708/23095973/eb69b3f0-f613-11e6-809f-93b507bd1a78.png)

**Comment by bastimeyer** [comment]
I'm unable to reproduce this on `master` and `v1.1.1`. Does this happen all the time when opening the top games menu? Could this be another Twitch API issue where no data is included the the response?

**Comment by cprn** [comment]
It happens for me every time I run the app, reinstall doesn't help. How do I check the response? Can't find any logs for this thing. Run in terminal says nothing.

**Comment by bastimeyer** [comment]
API responses are not being logged. You need to clone the repo and follow the instructions [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/CONTRIBUTING.md#developing-and-building). This should be simple if you've already tried the -git AUR package, since node, npm, bower and grunt-cli should have already been installed and packages been cached.

**Comment by cprn** [comment]
For some reason all the `<li/>` elements have `width: 0`. Any ideas? 

![2017-02-22-021026_1273x1052_scrot](https://cloud.githubusercontent.com/assets/6132708/23192518/3313302c-f8a4-11e6-96ff-d4c22f6691b9.png)

**Comment by bastimeyer** [comment]
That is very weird. It looks like the css media queries are not working.

The number of items per row is defined here
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/styles/components/list/GameItemComponent.less#L13
and calculated by this mixin
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/styles/mixins.less#L97-L153

This yields the following css:
```css
.game-item-component {
  position: relative;
  min-height: 235px;
  margin-bottom: 20px;
  overflow: hidden;
  cursor: pointer;
}
@media (max-width: 1136px) and (min-width: 956px) {
  .game-item-component {
    width: 23%;
    margin-right: 2.66666667%;
  }
  .game-item-component:nth-of-type( 4n) {
    margin-right: 0;
  }
}
@media (max-width: 1317px) and (min-width: 1137px) {
  .game-item-component {
    width: 18.4%;
    margin-right: 2%;
  }
  .game-item-component:nth-of-type( 5n) {
    margin-right: 0;
  }
}
@media (max-width: 1497px) and (min-width: 1318px) {
  .game-item-component {
    width: 15.33333333%;
    margin-right: 1.6%;
  }
  .game-item-component:nth-of-type( 6n) {
    margin-right: 0;
  }
}
@media (min-width: 1498px) {
  .game-item-component {
    width: 13.14285714%;
    margin-right: 1.33333333%;
  }
  .game-item-component:nth-of-type( 7n) {
    margin-right: 0;
  }
}
```

As you can see, the last media query doesn't have an upper boundary. The first one should match all supported resolutions (app window min sizes are 960x540 (quarter of 1920x1080)).

What's your current display setting? Please run `xrandr` and post the results.

I'm not sure if the media queries are to be blamed here. Can you please open the `main.css` file in the dev tools ("Sources" tab) and remove all of these media queries except the first one (search for ".game-item-component") and then change its constraints a bit? Ctrl+s updates the stylesheets...
