### ISSUE TITLE
Weird thumbnail scaling

### ISSUE THREAD

**Issue by h1z1** [streamlink/streamlink-twitch-gui#596]
## Bug report

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Linux

**Streamlink Twitch GUI version:**  
1.6.0
**Streamlink version:**  
0.14.2+24

**Configuration details:**  
Standard install

### Description
Not sure if at some point today either twitch pushed an update or something else broke - Thumbnails on streams are scaled down way too much now.  Aspect ratio matches the source stream.

### Expected / Actual behavior

Uniform thumbnails.

### Reproduction steps
1. ... Launch app
2. ... Browse by Streams or Game type

### Log output
NA

### Additional comments, screenshots, etc.
See attached screenshot

**Comment by bastimeyer** [comment]
> See attached screenshot

You didn't include any screenshots...

Are you talking about a broken layout or just the pictures themselves? What's the res and scaling of your desktop?

**Comment by h1z1** [comment]
Interesting.. Blame Github/MS for that.  Swear it was attached.

__
![twitchwtf](https://user-images.githubusercontent.com/17220053/44965452-b8809f80-af03-11e8-8ec3-f9259613d3f7.png)

Fwiw it appears OK now.

**Comment by bastimeyer** [comment]
That looks weird... This must be an issue with the CSS media queries and the window size and/or DPI scaling, but I can't tell you exactly what is going on from just seeing your screenshot.

The StreamItemComponent's width and height are independent of the size of the loaded preview image, so it doesn't matter which content is being shown. The component gets its width from the ContentListComponent where it is embedded into and the height is being calculated by the defined aspect ratio of the component's preview image.

The ContentListComponent sets dynamic `width` and `margin-right` properties for each of its elements via CSS media queries, depending on the size of the window and the application's/desktop's DPI scaling. Since your screenshot is showing no space between each list element, I guess one of these CSS media queries is not matching, which is weird.

Here is the CSS that's being generated and as you can see, the second last media query should match the window size of the screenshot you've posted.
```css
@media (min-width: 1px) and (max-width: 1196px) {
  .stream-item-component {
    width: 30.66666667%;
    margin-right: 4%;
  }
  .stream-item-component:nth-of-type( 3n) {
    margin-right: 0;
  }
}
@media (min-width: 1197px) and (max-width: 1437px) {
  .stream-item-component {
    width: 23%;
    margin-right: 2.66666667%;
  }
  .stream-item-component:nth-of-type( 4n) {
    margin-right: 0;
  }
}
@media (min-width: 1438px) and (max-width: 1678px) {
  .stream-item-component {
    width: 18.4%;
    margin-right: 2%;
  }
  .stream-item-component:nth-of-type( 5n) {
    margin-right: 0;
  }
}
@media (min-width: 1679px) and (max-width: 1919px) {
  .stream-item-component {
    width: 15.33333333%;
    margin-right: 1.6%;
  }
  .stream-item-component:nth-of-type( 6n) {
    margin-right: 0;
  }
}
@media (min-width: 1920px) {
  .stream-item-component {
    width: 13.14285714%;
    margin-right: 1.33333333%;
  }
  .stream-item-component:nth-of-type( 7n) {
    margin-right: 0;
  }
}
```
